prefix recipe-kb: <http://idea.rpi.edu/heals/kb/>
SELECT DISTINCT ?cooc_ing (COUNT(distinct ?recipe) as ?cooc_count)
WHERE {{
    ?ing_A recipe-kb:ing_name {ing_uri_A}.
    ?ing_B recipe-kb:ing_name {ing_uri_B}.
    ?recipe recipe-kb:uses ?ing_A;
        recipe-kb:uses ?ing_B;
        recipe-kb:uses ?cooc_ing_use.
    ?cooc_ing_use recipe-kb:ing_name ?cooc_ing.
}}
GROUP BY ?cooc_ing
HAVING (COUNT(distinct ?recipe) > 0)